name: CI Process
run-name: ${{github.actor}} is learning Github Actions
on: [push]
jobs:
  behave-testing:
    # Setup of simple OS of choice
    # Create VM with ubuntu OS
    runs-on: ubuntu-latest
    steps:
    # Setup of environment for test
      - name: Checkout
        uses: actions/checkout@v4 
      - name: List repo
        run: |
          ls
          
      # install python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' 

      # install behave
      - name: Setup Behave
        uses: BSFishy/pip-action@v1
        with:
          packages: |
            behave

      # Run behave
      - name: Run behave test
        uses: cryptic-wizard/run-behave-tests@v0.4.0
        with:
          test-output-name: results.txt
